# Generated by Django 6.0.3 on 2026-03-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Имя пользователя',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Фамилия пользователя',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия пользователя'),
            preserve_default=False,
        ),
    ]
