# Generated by Django 6.0.3 on 2026-03-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_имя_пользователя_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='value',
            new_name='Значение',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='Описание',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='Пользователь',
        ),
    ]
