# Generated by Django 6.0.3 on 2026-03-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_value_contact_значение_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Пользователь',
            new_name='user',
        ),
    ]
