# Generated by Django 6.0.3 on 2026-03-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'Параметры продукта', 'verbose_name_plural': 'Параметры продуктов'},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'Информация о продукте', 'verbose_name_plural': 'Информация о продуктах'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='Статус заказа',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='Название магазина',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Статус заказа',
            field=models.CharField(choices=[('new', 'Заказ оформлен'), ('shipped', 'Заказ в пути'), ('ready', 'Можете забрать заказ'), ('canceled', 'Заказ отменён')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название магазина'),
            preserve_default=False,
        ),
    ]
