# Generated by Django 6.0.3 on 2026-03-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_options_alter_productparameter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Название категории',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='Наименование параметра',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Наименование параметра'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
