# Generated by Django 6.0.3 on 2026-03-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_category_название_категории_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Категория',
        ),
    ]
