# Generated by Django 6.0.3 on 2026-03-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_category_product_категория'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='Пользователь',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Описание',
        ),
        migrations.RenameField(
            model_name='productparameter',
            old_name='shop_product',
            new_name='ID Информации о продукте',
        ),
        migrations.RenameField(
            model_name='productparameter',
            old_name='parameter',
            new_name='ID Параметра',
        ),
        migrations.RenameField(
            model_name='productparameter',
            old_name='value',
            new_name='Значение',
        ),
    ]
