# Generated by Django 6.0.3 on 2026-03-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_user_order_пользователь_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproduct',
            old_name='description',
            new_name='Описание',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='price',
            new_name='Рекомендованная розничная цена',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='price_rrc',
            new_name='Цена',
        ),
    ]
