# Generated by Django 6.0.3 on 2026-03-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('Название категории', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Дата и время оформления заказа', models.DateField()),
                ('Статус заказа', models.CharField(choices=[('new', 'Заказ оформлен'), ('shipped', 'Заказ в пути'), ('ready', 'Можете забрать заказ'), ('canceled', 'Заказ отменён')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('parametr_id', models.AutoField(primary_key=True, serialize=False)),
                ('Наименование параметра', models.CharField(max_length=50)),
                ('Единица измерения', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название магазина')),
                ('Прайс-лист', models.FileField(upload_to='')),
                ('Ссылка на сайт', models.URLField()),
                ('Номер телефона', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Имя пользователя', models.CharField(max_length=50)),
                ('Фамилия пользователя', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Наименование продукта', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('product_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('Информация о продукте', models.CharField(max_length=100)),
                ('Количество', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rice_rrc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.product')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ProductParametr',
            fields=[
                ('product_parametr_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parametr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.parametr')),
                ('product_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('Количество', models.IntegerField(default=0)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.product')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.shop')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('Назначение контактных данных', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
    ]
